export const CHANGE_FILTERS = '@@CHANGE_FILTERS';
export const FETCH_SEARCH_FILTER = '@@FETCH_SEARCH_FILTER';
export const SET_SEARCH_FILTER = '@@SET_SEARCH_FILTER';
export const CLEAN_SEARCH_FILTER = '@@CLEAN_SEARCH_FILTER';
export const SET_AGE_FILTER = '@@SET_AGE_FILTER';
export const SET_GENDER_FILTER = '@@SET_GENDER_FILTER';
export const CLEAN_FILTERS = '@@CLEAN_FILTERS';
